{% set name = "mlxtend" %}
{% set version = "0.23.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e58b2ea6148043297529e15c39ded540f62d04e044d75c2497afbe4682002675

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy >=1.14.6
    - scipy >=1.1.0
    - scikit-learn >=0.20.1
    - pandas >=0.23.4
    - matplotlib-base >=1.5.1

test:
  requires:
    - nose
    - python {{ python_min }}
  imports:
    - mlxtend
    - mlxtend._base
    - mlxtend.classifier
    - mlxtend.cluster
    - mlxtend.data
    - mlxtend.evaluate
    - mlxtend.externals
    - mlxtend.feature_extraction
    - mlxtend.feature_selection
    - mlxtend.file_io
    - mlxtend.frequent_patterns
    - mlxtend.math
    - mlxtend.plotting
    - mlxtend.preprocessing
    - mlxtend.regressor
    - mlxtend.text
    - mlxtend.utils

about:
  home: https://github.com/rasbt/mlxtend
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE-BSD3.txt
  summary: Machine Learning Library Extensions
  description: >
    A library of Python tools and extensions for data science and machine learning.

    Contact =============

    If you have any questions or comments about mlxtend, please feel free to contact me via eMail: mail@sebastianraschka.com or Twitter: https://twitter.com/rasbt

    This project is hosted at https://github.com/rasbt/mlxtend The documentation can be found at http://rasbt.github.io/mlxtend/
  doc_url: http://rasbt.github.io/mlxtend/
  dev_url: https://github.com/rasbt/mlxtend

extra:
  recipe-maintainers:
    - rasbt
